spring:
  application:
    name: smart-store-local
  docker:
    compose:
      enabled: true  # Docker Compose 자동 실행

  jpa:
    hibernate:
      ddl-auto: create-drop    # 스키마 자동 생성 전략 
    show-sql: true        # 실행되는 SQL 출력 (디버깅용)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true   #  SQL 포맷팅 활성화
        highlight_sql: true    #  SQL 하이라이트 활성화
        use_sql_comments: true  #  SQL 주석 활성화
        hbm2ddl: 
          auto: create-drop

  devtools:
    livereload:
      enabled: true

      
# loggin
logging:
  level:
    root: INFO
    com.smartstore: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE # orm binding
    org.springframework.security: DEBUG

