spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/default_db}
    username: ${DB_USERNAME:default_user}
    password: ${DB_PASSWORD:default_password}
  jpa:
    hibernate:
      ddl-auto: validate  # 운영에서는 update 사용 금지, validate 권장
    show-sql: false
    
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"  #  운영 환경에서는 제한된 엔드포인트만 공개
  endpoint:
    health:
      show-details: never  #  자세한 시스템 정보 숨김
  security:
    enabled: true  #  보안을 적용하여 접근 제한
# # loggin
logging:
  level:
    org.hibernate.SQL: ERROR  # SQL 실행 중 오류만 로그에 남김
    org.hibernate.orm.jdbc.bind: ERROR  # SQL 바인딩 값 로그 비활성화