spring:
  application:
    name: smart-store-dev
  # docker:
    # compose:
    #   enabled: true  # Docker Compose 자동 실행

  jpa:
    hibernate:
      ddl-auto: update    # 스키마 자동 생성 전략 
    show-sql: true        # 실행되는 SQL 출력 (디버깅용)
    properties:
      hibernate:
        format_sql: true   #  SQL 포맷팅 활성화
        highlight_sql: true    #  SQL 하이라이트 활성화
        use_sql_comments: true  #  SQL 주석 활성화
        hbm2ddl: 
          auto: update
          import_files_sql_extractor:
            org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor

  devtools:
    livereload:
      enabled: true

management:

  endpoints:
    web:
      exposure:
        include: "*"  #  모든 Actuator 엔드포인트 활성화
  endpoint:
    health:
      show-details: always  #  health 상세 정보 표시
      
# loggin
logging:
  level:
    root: INFO
    com.smartstore: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE # orm binding
    org.springframework.security: DEBUG

# swagger
springdoc:
  api-docs:
    path: /swagger/api-docs
  swagger-ui:
    path: /swagger/index.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true
  use-management-port: false
  default-flat-param-object: true

